import { describe,it,expect } from 'vitest'
import { plans, stage, countAdaptation, canAdvance, validSet, emptySet, emptySymptoms, hasRedFlag, fullyCompleted, keyFor, prescription, type Workout } from './model'
function session(id:string):Workout{return {id,plan:plans('adaptation')[0],phase:'adaptation',start:'2020-01-01',status:'completed',eligible:true,logs:{},deferred:[],pre:emptySymptoms(),post:emptySymptoms(),rpeTarget:'5–6'}}
describe('readaptação por sessões e lista livre',()=>{
 it('mantém 3 principais e extras independentes',()=>{const p=plans('adaptation');expect(p.filter(x=>!x.optional).map(x=>x.day)).toEqual([1,2,3]);expect(p.filter(x=>x.optional).map(x=>x.day)).toEqual([4,5])})
 it('exclui extras, parciais, cancelados e duplicações, independentemente da data',()=>{const a=session('1');expect(countAdaptation([a,a,{...session('2'),plan:plans('adaptation')[3]},{...session('3'),eligible:false},{...session('4'),status:'cancelled'},{...session('5'),phase:'consolidation'}])).toBe(1);expect([0,2,3,6,9,12].map(stage)).toEqual([1,1,2,3,4,4])})
 it('não troca ficha por contagem sem respostas positivas',()=>{expect(canAdvance(12,12,'yes','yes','yes','yes')).toBe(true);expect(canAdvance(11,12,'yes','yes','yes','yes')).toBe(false);expect(canAdvance(12,12,'yes','','yes','yes')).toBe(false);expect(canAdvance(12,12,'yes','yes','yes','no')).toBe(false)})
 it('não interpreta dor habitual alta como novo sinal neurológico',()=>{expect(hasRedFlag({...emptySymptoms(),pain:'6',neuro:'no'})).toBe(false);expect(hasRedFlag({...emptySymptoms(),urgent:'yes'})).toBe(true)})
 it('valida unidades e preserva RPE ausente',()=>{const i=plans('adaptation')[0].items[1];expect(validSet(i,{...emptySet(),reps:'12'})).toBe(true);expect(validSet(i,{...emptySet(),reps:'1.5'})).toBe(false);expect(validSet(i,{...emptySet(),reps:'12',rpe:'11'})).toBe(false);expect(validSet(i,{...emptySet(),reps:'12',weight:'-1'})).toBe(false);expect(prescription({...i,seconds:20})).toBe('2 × 20 s')})
 it('permite concluir séries fora da ordem, mas exige todos os exercícios principais para elegibilidade',()=>{const w=session('1');const strength=w.plan.items.filter(i=>!['cardio','aquecimento'].includes(i.category));for(const i of [...strength].reverse())for(let n=i.sets-1;n>=0;n--)w.logs[keyFor(i,n)]={...emptySet(),reps:'10',done:true};expect(fullyCompleted(w)).toBe(true);delete w.logs[keyFor(strength[0],0)];expect(fullyCompleted(w)).toBe(false)})
 it('a nova ficha não modifica o snapshot da anterior',()=>{const a=plans('adaptation');const before=JSON.stringify(a);const c=plans('consolidation');expect(JSON.stringify(a)).toBe(before);expect(c[0].version).not.toBe(a[0].version);expect(c[0].items[1].max).toBe(14);expect(a[0].items[1].max).toBe(12)})
})
