import { useEffect, useRef, useState } from 'react'
import type { User } from '@supabase/supabase-js'
import { allRecords, exportBackup, putRecord, resolveConflict, syncRecords, type Kind, type LocalRecord } from './store'
import { loadLegacy } from './legacy'
import { canAdvance, cardioMinutes, countAdaptation, emptySet, emptySymptoms, fullyCompleted, hasRedFlag, initialSettings, isCardio, keyFor, localDate, plans, prescription, rpeTarget, validSet, weekStart, type Item, type Plan, type SetLog, type Settings, type Symptoms, type Workout } from './model'
import './tracker.css'

const settingsId='00000000-0000-4000-8000-000000000001'
const days=['','Segunda','Terça','Quarta','Quinta','Sexta']
const errorText=(e:unknown)=>e instanceof Error?e.message:typeof e==='object'&&e&&'message' in e?String(e.message):'Não foi possível sincronizar. Seus registros locais foram mantidos.'
function download(name:string,data:unknown){const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}

export function HomePage({user,onSignOut}:{user:User;onSignOut:()=>Promise<void>}){
 const [records,setRecords]=useState<LocalRecord[]>([]),[ready,setReady]=useState(false),[tab,setTab]=useState('today'),[active,setActive]=useState<string|null>(null),[pre,setPre]=useState<Plan|null>(null)
 const [message,setMessage]=useState(''),[syncing,setSyncing]=useState(false),[writing,setWriting]=useState(0),[fatal,setFatal]=useState(false)
 const failedIds=useRef(new Set<string>())
 const rows=useRef<LocalRecord[]>([]),pending=useRef(0),writeChain=useRef(Promise.resolve()),mounted=useRef(true)
 const assign=(r:LocalRecord[])=>{rows.current=r;setRecords(r)}
 async function refresh(){if(pending.current||failedIds.current.size)return;const r=await allRecords(user.id);if(mounted.current&&!pending.current)assign(r)}
 async function sync(){if(pending.current||failedIds.current.size||!navigator.onLine)return;setSyncing(true);try{await syncRecords(user.id);setMessage('')}catch(e){setMessage(errorText(e))}finally{if(mounted.current){setSyncing(false);await refresh()}}}
 useEffect(()=>{
  mounted.current=true
  const changed=()=>{void refresh().catch(e=>setMessage(errorText(e)))}
  const online=()=>{void sync()}
  void allRecords(user.id).then(async r=>{if(!mounted.current)return;assign(r);setReady(true);if(navigator.onLine){try{await syncRecords(user.id);await loadLegacy(user.id);await refresh()}catch(e){setMessage(errorText(e))}}}).catch(e=>{setFatal(true);setReady(true);setMessage(errorText(e))})
  window.addEventListener('tracker-change',changed);window.addEventListener('online',online)
  const timer=setInterval(online,20000)
  const unload=(e:BeforeUnloadEvent)=>{if(pending.current||failedIds.current.size){e.preventDefault();e.returnValue=''}}
  window.addEventListener('beforeunload',unload)
  return()=>{mounted.current=false;clearInterval(timer);window.removeEventListener('tracker-change',changed);window.removeEventListener('online',online);window.removeEventListener('beforeunload',unload)}
 },[user.id])
 async function save(id:string,kind:Kind,payload:any){
  const old=rows.current.find(r=>r.id===id)
  assign([...rows.current.filter(r=>r.id!==id),{...old,key:`${user.id}:${id}`,id,user:user.id,kind,payload,revision:old?.revision??0,mutation:old?.mutation??'',dirty:true}])
  pending.current++;setWriting(pending.current)
  const job=writeChain.current.then(()=>putRecord(user.id,id,kind,payload))
  writeChain.current=job.catch(()=>{})
  try{await job;failedIds.current.delete(id);setFatal(failedIds.current.size>0)}catch(e){failedIds.current.add(id);setFatal(true);setMessage('É necessário liberar espaço no aparelho. Exporte seus registros antes de sair. '+errorText(e));throw e}finally{pending.current--;setWriting(pending.current)}
 }
 async function cancelWorkout(w:Workout){
  if(w.status!=='active'||!window.confirm('Cancelar este treino? Ele sairá da retomada e não contará na evolução.'))return
  try{await save(w.id,'session',{...w,status:'cancelled',eligible:false,end:new Date().toISOString()});setActive(null);setTab('today');setMessage('Treino cancelado. Você já pode iniciar um novo.');void sync()}catch(e){setMessage(errorText(e))}
 }
 const settings:Settings=records.find(r=>r.kind==='settings'&&r.id===settingsId)?.payload??initialSettings
 const sessions:Workout[]=records.filter(r=>r.kind==='session').map(r=>r.payload)
 const count=countAdaptation(sessions),catalog=plans(settings.phase)
 const current=sessions.find(s=>s.id===active&&s.status!=='cancelled')
 const completed=sessions.filter(s=>s.status==='completed').sort((a,b)=>b.start.localeCompare(a.start))
 const week=completed.filter(s=>localDate(s.start)>=weekStart())
 const chosen=catalog.find(p=>p.day===new Date(new Date().toLocaleString('en-US',{timeZone:'America/Sao_Paulo'})).getDay())
 const dirty=records.filter(r=>r.dirty).length,conflicts=records.filter(r=>r.conflict)
 const update=(w:Workout)=>{const next=w.status==='completed'?{...w,eligible:!w.plan.optional&&fullyCompleted(w),partial:!w.plan.optional&&!fullyCompleted(w)}:w;void save(w.id,'session',next).catch(()=>{})}
 if(!ready)return <main className="center-state"><div className="spinner"/><p>Abrindo seus registros…</p></main>
 return <div className="app-shell tracker"><header className="topbar"><div><p className="eyebrow"><svg className="brand-cross" viewBox="0 0 24 24" aria-hidden="true"><path d="M4 2H20C16 6 14 8 14 10C16 10 18 8 22 4V20C18 16 16 14 14 14C14 16 16 18 20 22H4C8 18 10 16 10 14C8 14 6 16 2 20V4C6 8 8 10 10 10C10 8 8 6 4 2Z" fill="currentColor"/></svg>{current?`TREINO ${current.plan.code}`:'PLANO DE TREINO'}</p><h1>{current?current.plan.name:'Seu ritmo, seu treino'}</h1></div></header>
  <div className="sync-bar" role="status">{writing?'Salvando no aparelho…':fatal?'Falha no armazenamento local':syncing?'Sincronizando…':dirty?`${dirty} registro(s) no aparelho · envio pendente`:navigator.onLine?'Registros sincronizados':'Offline · salve normalmente'}<button onClick={()=>void sync()} disabled={syncing||writing>0}>Sincronizar</button></div>
  <main className="content">
   {fatal&&<button onClick={()=>download('plano-de-treino-emergencia.json',{format:'training-tracker-v3',records:rows.current})}>Exportar registros antes de sair</button>}
   {fatal&&<button className="secondary-button" onClick={()=>{for(const id of failedIds.current){const row=rows.current.find(r=>r.id===id);if(row)void save(row.id,row.kind,row.payload).catch(()=>{})}}}>Tentar salvar no aparelho novamente</button>}
   {message&&<div className="alert yellow">{message}<button onClick={()=>setMessage('')}>Fechar</button></div>}
   {conflicts.map(r=><section className="alert yellow" key={r.id}><strong>Este registro também foi alterado em outro aparelho.</strong><p>Compare as cópias antes de escolher. A cópia não escolhida pode ser exportada.</p><details><summary>Comparar versões</summary><h4>Neste aparelho</h4><pre>{JSON.stringify(r.payload,null,2)}</pre><h4>Na nuvem</h4><pre>{JSON.stringify(r.conflict.payload,null,2)}</pre></details><button onClick={()=>download('conflito-treino.json',{local:r.payload,cloud:r.conflict.payload})}>Exportar ambas</button><button onClick={()=>void resolveConflict(user.id,r.id,'remote').then(refresh)}>Usar nuvem</button><button onClick={()=>void resolveConflict(user.id,r.id,'local').then(sync)}>Manter este aparelho</button></section>)}
   {current?<WorkoutEditor cancel={()=>cancelWorkout(current)} workout={current} history={completed.filter(s=>s.id!==current.id)} update={update} saving={writing>0||fatal} back={()=>setActive(null)} finish={async w=>{await save(w.id,'session',w);setActive(null);setTab('history');void sync()}}/>:
    pre?<PreWorkout plan={pre} back={()=>setPre(null)} start={async symptoms=>{const id=crypto.randomUUID();const w:Workout={id,plan:structuredClone(pre),phase:settings.phase,start:new Date().toISOString(),status:'active',eligible:false,logs:{},deferred:[],pre:symptoms,post:emptySymptoms(),rpeTarget:settings.phase==='adaptation'?rpeTarget(count):'6–7'};await save(id,'session',w);setPre(null);setActive(id);void sync()}}/>:<>
    {tab==='today'&&<>
     {sessions.filter(s=>s.status==='active').map(s=><section className="hero-card" key={s.id}><h2>Treino em andamento</h2><p>{s.plan.code} · {s.plan.name}</p><button className="primary-button" onClick={()=>setActive(s.id)}>Retomar treino</button><button className="secondary-button" disabled={writing>0||fatal} onClick={()=>void cancelWorkout(s)}>Cancelar treino</button></section>)}
     <section className="hero-card"><span className="badge">{chosen?days[chosen.day]:'DESCANSO'}</span><h2>{chosen?`${chosen.code} · ${chosen.name}`:'Hoje é dia de descanso'}</h2><p>Segunda, terça e quarta: principais. Quinta e sexta: extras, quando houver recuperação e disponibilidade.</p>{chosen&&<button className="primary-button" disabled={sessions.some(s=>s.status==='active')} onClick={()=>setPre(chosen)}>Iniciar treino</button>}</section>
     <div className="metric-grid"><article><strong>{week.filter(s=>!s.plan.optional&&!s.partial).length}/3</strong><span>Principais nesta semana</span></article><article><strong>{week.filter(s=>s.plan.optional).length}</strong><span>Extras nesta semana</span></article><article><strong>{Math.round(week.reduce((n,s)=>n+cardioMinutes(s),0))} min</strong><span>Cardio na semana</span></article><article><strong>{count}/{settings.checkpoint}</strong><span>Sessões de adaptação</span></article></div>
     <section className="plain-card"><h2>{settings.phase==='adaptation'?'Readaptação':'Consolidação'}</h2><p>{settings.phase==='adaptation'?`Próxima sessão: RPE ${rpeTarget(count)}. A referência de esforço muda a cada três treinos principais concluídos, nunca pela data.`:'RPE 6–7. A ficha mudou, mas as cargas não aumentam automaticamente.'}</p><p>Treinos extras não antecipam a troca. Sessões parciais ficam no histórico, sem avançar o contador. O histórico anterior com séries realizadas foi preservado.</p></section>
     {settings.phase==='adaptation'&&count>=settings.checkpoint&&<Review settings={settings} recent={completed.filter(s=>!s.plan.optional).slice(0,3)} count={count} save={async s=>{await save(settingsId,'settings',s);void sync()}} disabled={sessions.some(s=>s.status==='active')}/>}
     <Safety/>
    </>}
    {tab==='workouts'&&catalog.map(p=><section className="plain-card" key={p.code}><span className="badge">{days[p.day]} · {p.optional?'EXTRA':'PRINCIPAL'}</span><h2>{p.code} · {p.name}</h2><p>{p.optional?'Opcional: não substitui os principais.':'Duas séries nos exercícios de força; carga conservadora e sem falha.'}</p><ul>{p.items.map(i=><li key={i.key}>{i.name} · {prescription(i)}</li>)}</ul><button className="primary-button" disabled={sessions.some(s=>s.status==='active')} onClick={()=>setPre(p)}>Iniciar este treino</button></section>)}
    {tab==='history'&&<><h2>Histórico preservado</h2>{completed.length===0&&<p>Seus treinos aparecerão aqui após a conclusão.</p>}{completed.map(w=><details className="plain-card" key={w.id}><summary>{localDate(w.start)} · {w.plan.code} · {w.partial?'Parcial':w.plan.optional?'Extra':'Principal'}</summary><p>{w.plan.name} · {w.plan.version}</p><p>{w.end?Math.max(1,Math.round((Date.parse(w.end)-Date.parse(w.start))/60000)):'—'} min · Dor: {w.pre.pain||'não informada'} → {w.post.pain||'não informada'}</p>{w.plan.items.map(i=><div key={i.key}><strong>{i.name}</strong><p>{Array.from({length:i.sets},(_,n)=>{const s=w.logs[keyFor(i,n)];return s?.done?`S${n+1}: ${s.weight?`${s.weight} kg · `:''}${i.seconds?`${s.seconds}s`:`${s.reps} reps`} · RPE ${s.rpe||'—'}${s.note?` · ${s.note}`:''}`:null}).filter(Boolean).join(' / ')||'Não realizado'}</p></div>)}<p>{w.post.note}</p><button onClick={()=>setActive(w.id)}>Revisar ou corrigir registros</button></details>)}</>}
    {tab==='checkin'&&<Checkin records={records} week={week} save={save}/>}
    {tab==='more'&&<><Measurements records={records} save={save}/><section className="plain-card"><h2>Dados e conta</h2><p>Abra o app conectado ao menos uma vez para preparar o uso offline. Os dados ficam separados por conta neste aparelho.</p><button className="secondary-button" onClick={()=>fatal?download('plano-de-treino-backup.json',{format:'training-tracker-v3',records:rows.current}):void exportBackup(user.id).then(data=>download('plano-de-treino-backup.json',data))}>Exportar backup completo</button><p>Se houver conflito entre aparelhos, o app pede qual versão manter. Evite editar o mesmo treino simultaneamente em dois aparelhos.</p><button className="danger-button" disabled={writing>0||dirty>0||fatal} onClick={()=>void onSignOut()}>Sair da conta</button>{dirty>0&&<p>Envie os registros pendentes antes de sair.</p>}</section><Safety/><section className="plain-card"><h3>Como progredir</h3><p>Primeiro aumente repetições. Só considere um pequeno aumento de carga ao atingir o topo da faixa em todas as séries, com RPE na meta, boa técnica, amplitude adequada, recuperação suficiente e sem piora lombar ou novos sintomas. Nenhuma carga sobe por passagem de tempo.</p><p>Versão 3.0 · treinos em lista e adaptação por sessões.</p></section></>}
   </>}
  </main>
  {!current&&!pre&&<nav className="bottom-nav">{[['today','Hoje'],['workouts','Treinos'],['history','Histórico'],['checkin','Check-in'],['more','Mais']].map(([key,label])=><button key={key} className={tab===key?'active':''} onClick={()=>setTab(key)}>{label}</button>)}</nav>}
 </div>
}

function NumberField({label,value,change,max,min=0,integer=false}:{label:string;value:string;change:(s:string)=>void;max?:number;min?:number;integer?:boolean}){return <label><span className="field-label">{label}</span><input type="number" inputMode={integer?'numeric':'decimal'} min={min} max={max} step={integer?1:0.5} value={value} onChange={e=>change(e.target.value)}/></label>}
function Choice({label,value,change,options=[['yes','Sim'],['no','Não']]}:{label:string;value:string;change:(s:string)=>void;options?:string[][]}){return <label>{label}<select value={value} onChange={e=>change(e.target.value)}><option value="">Não informado</option>{options.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>}
function Safety(){return <section className="plain-card"><h3>Lombar: compare com seu padrão habitual</h3><p>Sem piora ou sintomas novos: continue com controle. Se piorar durante as séries, reduza amplitude e carga; retire o exercício se a piora continuar.</p><p>Dor forte irradiada, dormência, formigamento significativo ou fraqueza nova: interrompa e procure avaliação. Alteração urinária/intestinal ou dormência perineal: procure atendimento de urgência.</p></section>}
function SymptomsForm({value,change,post=false}:{value:Symptoms;change:(s:Symptoms)=>void;post?:boolean}){const edit=(key:keyof Symptoms,v:string)=>change({...value,[key]:v});return <><div className="input-grid"><NumberField label="Dor lombar /10 (opcional)" value={value.pain} max={10} change={v=>edit('pain',v)}/><NumberField label={post?'Qualidade /5 (opcional)':'Energia /5 (opcional)'} value={(post?value.quality:value.energy)||''} min={1} max={5} integer change={v=>edit(post?'quality':'energy',v)}/></div><Choice label="A dor piorou ou mudou em relação ao habitual?" value={value.change} change={v=>edit('change',v)}/><Choice label="Irradiação forte, formigamento relevante, dormência ou fraqueza novos?" value={value.neuro} change={v=>edit('neuro',v)}/><details><summary>Outros sintomas e observações</summary><Choice label="Alteração urinária/intestinal ou dormência perineal?" value={value.urgent} change={v=>edit('urgent',v)}/><NumberField label="Recuperação /5 (opcional)" value={value.recovery||''} min={1} max={5} integer change={v=>edit('recovery',v)}/><label>Observações<textarea value={value.note||''} onChange={e=>edit('note',e.target.value)}/></label></details>{hasRedFlag(value)&&<div className="alert red">Interrompa o exercício e procure avaliação. Alterações urinárias/intestinal ou dormência perineal exigem atendimento de urgência.</div>}{value.change==='yes'&&!hasRedFlag(value)&&<p className="alert yellow">Reduza amplitude/carga e reavalie; retire o exercício se a piora continuar.</p>}</>}
function validSymptoms(s:Symptoms){return [['pain',0,10],['energy',1,5],['quality',1,5],['recovery',1,5]].every(([key,min,max])=>{const v=s[key as keyof Symptoms];return !v||Number.isFinite(Number(v))&&Number(v)>=Number(min)&&Number(v)<=Number(max)})}
function PreWorkout({plan,back,start}:{plan:Plan;back:()=>void;start:(s:Symptoms)=>Promise<void>}){const [symptoms,setSymptoms]=useState(emptySymptoms),[busy,setBusy]=useState(false),[error,setError]=useState('');return <section className="plain-card"><button onClick={back}>Voltar</button><h2>{plan.code} · {plan.name}</h2><p>Check rápido antes de começar. Valores não preenchidos ficam como não informados.</p><SymptomsForm value={symptoms} change={setSymptoms}/>{error&&<p role="alert">{error}</p>}<button className="primary-button" disabled={busy||hasRedFlag(symptoms)} onClick={()=>{if(!validSymptoms(symptoms))return setError('Confira as escalas de dor, energia e recuperação.');setBusy(true);void start(symptoms).catch(e=>{setError(errorText(e));setBusy(false)})}}>Começar treino</button></section>}

function WorkoutEditor({workout:w,history,update,saving,back,finish,cancel}:{cancel:()=>Promise<void>;workout:Workout;history:Workout[];update:(w:Workout)=>void;saving:boolean;back:()=>void;finish:(w:Workout)=>Promise<void>}){
 const [review,setReview]=useState(false),[timer,setTimer]=useState<{until:number;paused:number|null}|null>(null),[now,setNow]=useState(Date.now()),[error,setError]=useState(''),[busy,setBusy]=useState(false)
 useEffect(()=>{const id=setInterval(()=>setNow(Date.now()),500);return()=>clearInterval(id)},[])
 const left=timer?timer.paused??Math.max(0,Math.ceil((timer.until-now)/1000)):0
 const edit=(i:Item,n:number,p:Partial<SetLog>)=>{const key=keyFor(i,n);update({...w,logs:{...w.logs,[key]:{...(w.logs[key]??emptySet()),...p}}})}
 const count=w.plan.items.filter(i=>Array.from({length:i.sets},(_,n)=>w.logs[keyFor(i,n)]?.done).every(Boolean)).length
 const sorted=[...w.plan.items].sort((a,b)=>Number(w.deferred.includes(a.key))-Number(w.deferred.includes(b.key)))
 const unsaved=Object.values(w.logs).some(s=>!s.done&&[s.weight,s.reps,s.seconds,s.rpe].some(Boolean))
 function done(i:Item,n:number){const s=w.logs[keyFor(i,n)]??emptySet();if(!validSet(i,s)){setError('Informe repetições inteiras ou segundos realizados; carga até 2000 kg e RPE/dor entre 0 e 10.');return}edit(i,n,{done:true});setError('');if(i.rest){setNow(Date.now());setTimer({until:Date.now()+i.rest*1000,paused:null})}}
 if(review)return <section className="plain-card"><button onClick={()=>setReview(false)}>Voltar à lista</button><h2>Como foi o treino?</h2><p>{count}/{w.plan.items.length} exercícios completos. {fullyCompleted(w)?'Todas as séries principais foram registradas.':'Você pode concluir como parcial; o registro será preservado sem avançar a adaptação.'}</p><SymptomsForm post value={w.post} change={post=>update({...w,post})}/>{unsaved&&<p className="alert yellow">Há séries preenchidas sem concluir. Volte e confirme ou limpe esses campos antes de finalizar.</p>}{error&&<p role="alert">{error}</p>}<button className="primary-button" disabled={saving||busy||unsaved} onClick={()=>{if(!validSymptoms(w.post))return setError('Confira os valores das escalas.');setBusy(true);const full=fullyCompleted(w);void finish({...w,status:'completed',end:w.end??new Date().toISOString(),eligible:!w.plan.optional&&full,partial:!w.plan.optional&&!full}).catch(e=>setError(errorText(e))).finally(()=>setBusy(false))}}>{busy?'Salvando…':w.status==='completed'?'Salvar correções':fullyCompleted(w)||w.plan.optional?'Concluir treino':'Concluir treino parcial'}</button></section>
 return <><div className="workout-toolbar"><button disabled={saving} onClick={back}>Voltar · treino salvo</button><span>{count}/{w.plan.items.length} exercícios</span></div><progress className="workout-progress" max={w.plan.items.length} value={count} aria-label="Exercícios concluídos"/><p className="workout-hint">RPE {w.rpeTarget} · Você escolhe a ordem dos exercícios.</p>
 {left>0&&<div className="rest-timer sticky-timer"><span>Descanso</span><strong>{Math.floor(left/60)}:{String(left%60).padStart(2,'0')}</strong><button onClick={()=>setTimer(timer?.paused!==null?{until:Date.now()+left*1000,paused:null}:{until:0,paused:left})}>{timer?.paused!==null?'Retomar':'Pausar'}</button><button onClick={()=>setTimer(timer?.paused!==null?{until:0,paused:left+30}:{until:Date.now()+(left+30)*1000,paused:null})}>+30s</button><button onClick={()=>setTimer(null)}>Encerrar</button></div>}
 {error&&<div role="alert" className="alert yellow">{error}<button onClick={()=>setError('')}>Fechar</button></div>}
 {sorted.map(i=>{const previous=history.flatMap(h=>h.plan.items.filter(x=>x.name===i.name).flatMap(x=>Array.from({length:x.sets},(_,n)=>h.logs[keyFor(x,n)]))).find(s=>s?.done&&s.weight!=='');return <section className={`exercise-list-card ${w.deferred.includes(i.key)?'deferred':''}`} key={i.key}>
  <div className="exercise-heading"><div><h3>{i.name}</h3><p>{prescription(i)}{i.rest>0&&` · ${i.rest}–${i.restMax}s`}</p></div><button aria-label={`Adiar ou retomar ${i.name}`} onClick={()=>update({...w,deferred:w.deferred.includes(i.key)?w.deferred.filter(k=>k!==i.key):[...w.deferred,i.key]})}>{w.deferred.includes(i.key)?'Retomar':'Fazer depois'}</button></div>
  <div className="series-columns" aria-hidden="true"><span>Série</span><div className="series-inputs">{!isCardio(i)&&<span>kg</span>}<span>{i.seconds?'segundos':'reps'}</span><span>RPE</span></div><span/></div>
  {Array.from({length:i.sets},(_,n)=>{const s=w.logs[keyFor(i,n)]??emptySet();return <div className={`compact-set ${s.done?'confirmed':''}`} key={n}><span className="set-label">S{n+1}</span><div className="series-inputs">{!isCardio(i)&&<NumberField label="kg" value={s.weight} max={2000} change={weight=>edit(i,n,{weight,done:false})}/>}<NumberField label={i.seconds?'segundos':'reps'} value={i.seconds?s.seconds:s.reps} max={i.seconds?86400:1000} integer change={v=>edit(i,n,{[i.seconds?'seconds':'reps']:v,done:false})}/><NumberField label="RPE" value={s.rpe} max={10} change={rpe=>edit(i,n,{rpe,done:false})}/></div><button className={s.done?'set-done':'set-confirm'} aria-label={`${s.done?'Editar':'Concluir'} série ${n+1} de ${i.name}`} onClick={()=>s.done?edit(i,n,{done:false}):done(i,n)}>{s.done?'✓':'OK'}</button>
  </div>})}
  <details className="exercise-notes"><summary>Orientações e sintomas {previous&&<span className="last-weight"> · última carga: {previous.weight} kg</span>}</summary><p>{i.notes}</p>{previous&&<p>Último registro: {previous.weight} kg · {previous.reps||'—'} reps · RPE {previous.rpe||'—'}. Não é uma recomendação automática de carga.</p>}
   {Array.from({length:i.sets},(_,n)=>{const s=w.logs[keyFor(i,n)]??emptySet();return <div key={n}>
    {previous&&!s.weight&&!isCardio(i)&&<button className="copy-weight" onClick={()=>edit(i,n,{weight:previous.weight,done:false})}>Série {n+1} · copiar última carga: {previous.weight} kg</button>}
       <fieldset className="series-notes"><legend>Série {n+1}</legend><NumberField label="Dor /10" value={s.pain||''} max={10} change={pain=>edit(i,n,{pain})}/><Choice label="Resposta da lombar" value={s.response||''} options={[["same","Sem piora"],["worse","Piorou"]]} change={response=>edit(i,n,{response})}/><Choice label="Técnica consistente?" value={s.technique||''} change={technique=>edit(i,n,{technique})}/><Choice label="Amplitude adequada?" value={s.amplitude||''} change={amplitude=>edit(i,n,{amplitude})}/><label>Equipamento usado, substituição ou observação<input value={s.note||''} onChange={e=>edit(i,n,{note:e.target.value})}/></label>{s.response==='worse'&&<p className="alert yellow">Reduza amplitude/carga e reavalie; retire o exercício se continuar piorando.</p>}</fieldset>
   </div>})}
  </details>
 </section>})}
 <button className="primary-button" disabled={saving} onClick={()=>setReview(true)}>Revisar e finalizar</button>{w.status==='active'&&<button className="secondary-button" disabled={saving} onClick={()=>void cancel()}>Cancelar treino</button>}<p>Você pode finalizar mesmo sem realizar todos os exercícios. Séries não realizadas não serão inventadas.</p>
 </>
}
function Review({settings,recent,count,save,disabled}:{settings:Settings;recent:Workout[];count:number;save:(s:Settings)=>Promise<void>;disabled:boolean}){
 const [answers,setAnswers]=useState(['','','','']),[busy,setBusy]=useState(false),[error,setError]=useState('')
 const recentAlert=recent.some(w=>hasRedFlag(w.pre)||hasRedFlag(w.post))
 const ready=!recentAlert&&canAdvance(count,settings.checkpoint,answers[0],answers[1],answers[2],answers[3])
 async function submit(advance:boolean){setBusy(true);try{await save({...settings,phase:advance?'consolidation':'adaptation',checkpoint:advance?settings.checkpoint:count+3,reviews:[...settings.reviews,{at:new Date().toISOString(),count,ready:advance}]})}catch(e){setError(errorText(e))}finally{setBusy(false)}}
 return <section className="plain-card"><span className="badge">REVISÃO DA ADAPTAÇÃO</span><h2>{count} treinos principais realizados</h2><p>Últimas sessões: {recent.map(w=>`${w.plan.code}: dor ${w.pre.pain||"—"} → ${w.post.pain||"—"}`).join("; ")}</p>{recentAlert&&<p className="alert red">Há sintomas de alerta nos registros recentes. Procure avaliação antes de avançar; mantenha a adaptação por enquanto.</p>}<p>A quantidade abre esta revisão; não determina sozinha que você está pronto. A próxima ficha mantém os exercícios conhecidos e duas séries, ampliando moderadamente a faixa de repetições dos exercícios de força. As cargas não sobem automaticamente.</p>{['Recuperação suficiente entre sessões?','Lombar estável, sem piora relevante?','Técnica e amplitude consistentes?','Sem novos sintomas neurológicos?'].map((label,i)=><Choice key={label} label={label} value={answers[i]} change={v=>setAnswers(a=>a.map((x,n)=>n===i?v:x))}/>)}<details><summary>Ver a ficha de consolidação</summary>{plans('consolidation').map(p=><div key={p.code}><strong>{p.code} · {p.name}</strong><ul>{p.items.map(i=><li key={i.key}>{i.name}: {prescription(i)}</li>)}</ul></div>)}</details>{error&&<p role="alert">{error}</p>}<button className="primary-button" disabled={!ready||busy||disabled} onClick={()=>void submit(true)}>Ativar ficha de consolidação</button><button className="secondary-button" disabled={busy||disabled} onClick={()=>void submit(false)}>Manter adaptação por mais 3 treinos</button>{disabled&&<p>Finalize o treino em andamento antes de trocar de ficha.</p>}</section>
}
function Checkin({records,week,save}:{records:LocalRecord[];week:Workout[];save:(id:string,kind:Kind,payload:any)=>Promise<void>}){
 const existing=records.find(r=>r.kind==='checkin'&&r.payload.week===weekStart())
 const [form,setForm]=useState<Record<string,string>>(existing?.payload.values??{}),[saved,setSaved]=useState(''),[busy,setBusy]=useState(false)
 const fields=[['weight','Peso kg',20,500],['waist','Cintura cm',20,400],['sleep','Sono /5',1,5],['energy','Energia /5',1,5],['recovery','Recuperação /5',1,5],['stress','Estresse /5',1,5],['pain','Dor média /10',0,10],['steps','Passos/dia',0,200000]] as const
 async function submit(){if(fields.some(([k,,min,max])=>form[k]&&(Number(form[k])<min||Number(form[k])>max||!Number.isFinite(Number(form[k])))))return setSaved('Confira os valores das escalas.');setBusy(true);try{await save(existing?.id??`00000000-0000-4000-9000-${weekStart().replaceAll('-','')}0000`,'checkin',{week:weekStart(),values:form,main:week.filter(w=>!w.plan.optional&&!w.partial).length,extras:week.filter(w=>w.plan.optional).length,cardio:week.reduce((n,w)=>n+cardioMinutes(w),0)});setSaved('Check-in salvo no aparelho.')}catch(e){setSaved(errorText(e))}finally{setBusy(false)}}
 return <section className="plain-card"><h2>Check-in semanal</h2><p>Semana de {weekStart()} · {week.filter(w=>!w.plan.optional&&!w.partial).length}/3 principais · {week.filter(w=>w.plan.optional).length} extras</p><div className="input-grid">{fields.map(([key,label,min,max])=><NumberField key={key} label={`${label} (opcional)`} value={form[key]||''} min={min} max={max} change={v=>setForm(f=>({...f,[key]:v}))}/>)}</div><Choice label="Houve crise lombar?" value={form.flare||''} change={v=>setForm(f=>({...f,flare:v}))}/><Choice label="Houve novos sintomas neurológicos?" value={form.neuro||''} change={v=>setForm(f=>({...f,neuro:v}))}/><Choice label="Algum extra prejudicou a recuperação?" value={form.extraImpact||''} change={v=>setForm(f=>({...f,extraImpact:v}))}/><label>O que progrediu, o que incomodou e observações<textarea value={form.notes||''} onChange={e=>setForm(f=>({...f,notes:e.target.value}))}/></label><button className="primary-button" disabled={busy} onClick={()=>void submit()}>Salvar check-in</button><p role="status">{saved}</p><h3>Check-ins anteriores</h3>{records.filter(r=>r.kind==='checkin').sort((a,b)=>b.payload.week.localeCompare(a.payload.week)).map(r=><details key={r.id}><summary>{r.payload.week}</summary><p>Peso: {r.payload.values.weight||'—'} kg · Cintura: {r.payload.values.waist||'—'} cm</p><p>{r.payload.values.notes}</p></details>)}</section>
}

function Measurements({records,save}:{records:LocalRecord[];save:(id:string,kind:Kind,payload:any)=>Promise<void>}){
 const [weight,setWeight]=useState(''),[waist,setWaist]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false)
 return <section className="plain-card"><h2>Medidas corporais</h2><div className="input-grid"><NumberField label="Peso kg" value={weight} min={20} max={500} change={setWeight}/><NumberField label="Cintura cm" value={waist} min={20} max={400} change={setWaist}/></div><button className="secondary-button" disabled={busy} onClick={()=>{if((!weight&&!waist)||(weight&&(Number(weight)<20||Number(weight)>500))||(waist&&(Number(waist)<20||Number(waist)>400)))return setMessage('Informe peso ou cintura dentro da faixa válida.');setBusy(true);void save(crypto.randomUUID(),'measurement',{date:new Date().toISOString(),weight,waist}).then(()=>{setWeight('');setWaist('');setMessage('Medição salva no aparelho.')}).catch(e=>setMessage(errorText(e))).finally(()=>setBusy(false))}}>Salvar medição</button><p role="status">{message}</p>{records.filter(r=>r.kind==='measurement').sort((a,b)=>b.payload.date.localeCompare(a.payload.date)).map(r=><p key={r.id}>{localDate(r.payload.date)} · {r.payload.weight||'—'} kg · {r.payload.waist||'—'} cm</p>)}</section>
}
